### ISSUE TITLE
panprog - Maintaince margin is ignored when account is in a big overall loss

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#148]
panprog

medium

# Maintaince margin is ignored when account is in a big overall loss

## Summary

Maintaince margin (`mm` in the code) is ignored in all calculations throughout the code, when account is in a loss higher than overall maintaince margin. This leads to weaker protection against quick price moves both for partyA and partyB and possible loss of funds due to bad debt.

## Vulnerability Detail

The protocol uses maintaince margin (`mm`) as a risk protection measure against opening large positions with low allocated funds. However, maintaince margin is only applied when account unrealized pnl is positive (account is in a profit). If the account is in large loss (higher than `mm`), then `mm` is ignored, allowing to open positions (and deallocate) based on `cva` and `lf` values only.

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/libraries/LibAccount.sol#L42-L51

For example, 

1. If account has allocated balance of `100`, current locked `mm = 100` (consider `cva` = `lf` = 0 for simplicity) and unrealized profit of `50` (total available funds = `150`), it can unallocate max `50` (remaining available funds = `100`).

2. If account has allocated balance of `250`, current locked `mm = 100` and unrealized loss of `-100` (total available funds = `150`), it can unallocate max `150` (remaining available funds = `0`), which is a much riskier position, which can easily go into bad debt and a loss of profit for the other party.

Both cases (`balance = 100`, `upnl = 50` vs `balance = 250`, `upnl = -100`) are exactly the same from risk standpoint (it doesn't matter what the original balance was - what matters is that if position is closed right now, balance will be `150` in both cases), however the 2nd case (unrealized loss) is much riskier for the other party for no reason.

The same logic is also present in the following code:

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/libraries/LibAccount.sol#L65-L73

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/libraries/LibAccount.sol#L104-L113

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/libraries/LibAccount.sol#L131-L139

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/libraries/LibSolvency.sol#L50-L57

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/libraries/LibSolvency.sol#L61-L68

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/libraries/LibSolvency.sol#L74-L81

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/libraries/LibSolvency.sol#L85-L92

## Impact

Malicious partyA can intentionally put its account into large loss (there are a lot of ways to achieve it: open 2 different direction positions of the same size, one of them will be in a big loss while the other one in the same profit when price deviates from initial price; use partyB which is owned by the same user, to open position which is immediately in a large loss; etc). After that all positions opened by this partyA will ignore `mm`, so it can open risky positions with high risk of creating bad debt and a loss of funds for the other party of the trade.

## Code Snippet

Add this to any test, for example to `ClosePosition.behavior.ts`. It demonstrates that partyA can unallocate so that remaining funds are just $11 and still have positions opened with `mm = 500`.

```ts
  it("Ignore maintaince margin", async function () {
    const context: RunContext = this.context;

    this.user_allocated = decimal(1000);
    this.hedger_allocated = decimal(2000);

    this.user = new User(this.context, this.context.signers.user);
    await this.user.setup();
    await this.user.setBalances(this.user_allocated, this.user_allocated, this.user_allocated);

    this.hedger = new Hedger(this.context, this.context.signers.hedger);
    await this.hedger.setup();
    await this.hedger.setBalances(this.hedger_allocated, this.hedger_allocated);

    this.liquidator = new User(this.context, this.context.signers.liquidator);
    await this.liquidator.setup();

    await this.user.sendQuote(limitQuoteRequestBuilder().quantity(decimal(1000))
      .cva(decimal(1)).lf(decimal(10)).mm(decimal(500))
      .upnlSig(getDummySingleUpnlAndPriceSig(decimal(1), decimal(0))).build());
    await this.hedger.lockQuote(1);
    await this.hedger.openPosition(1, limitOpenRequestBuilder().filledAmount(decimal(1000)).build());

    var info = await this.user.getBalanceInfo();
    console.log("Allocated balance: " + info.allocatedBalances/1e18 + 
      " Locked: " + info.totalLocked / 1e18 + 
      " Locked mm: " + info.lockedMm / 1e18 + 
      " Locked cva+lf: "+(info.lockedCva.add(info.lockedLf))/1e18);

    console.log("With a loss of -900, deallocate 79");
    await context.accountFacet.connect(this.user.signer).deallocate(decimal(79), await getDummySingleUpnlSig(decimal(-900)));

    info = await this.user.getBalanceInfo();
    console.log("Allocated balance: " + info.allocatedBalances/1e18 + 
      " upnl: -900 remaining: " + (info.allocatedBalances/1e18 - 900) +
      " Locked: " + info.totalLocked / 1e18 + 
      " Locked mm: " + info.lockedMm / 1e18 + 
      " Locked cva+lf: "+(info.lockedCva.add(info.lockedLf))/1e18);
    
  });
```

## Tool used

Manual Review

## Recommendation

There is absolutely no reason to have different formula for unrealized profit and unrealized loss. Simply remove this difference and make the same formula for remaining funds regardless of profit or loss as:

`remainingAmount = allocatedAmount + upnl - lockedBalances.total()`

On a side but related note, your terms usage is different from industry standard, which is `initial margin` (margin required to open position or withdaw funds) and maintaince margin (margin required to keep position running, otherwise it gets liquidated). In your case, `cva + lf` is what `maintaince margin` is in the industry, and `cva +lf + mm` is what `initial margin` is in the industry, so your `mm` (maintaince margin) is slightly misleading term, because it's actually initial margin (used only for opening new positions and deallocations). I suggest you to re-think the terms usage to be more in-line with usual terms used.

**Comment by panprog** [comment]
Escalate

Let me get the facts straight on why the protocol needs `maintaince margin` (`mm`) at all: it is to prevent the user from being almost immediately liquidatable if he opens position at max leverage (`allocated balance = locked balance`). If there is no `maintaince margin` (`mm = 0`), then if `allocated balance = locked balance = cva + lf`, the position becomes liquidatable with any loss (so can become liquidatable almost immediately after being open). `Maintaince margin` aims to prevent it.

This issue is a valid medium, because `maintaince margin` is completely ignored when user account is in a big enough loss. So, let me state this again:

1. If a user is in a profit, `maintaince margin` is applied and he is protected from being almost immediately liquidatable if he opens with max margin and no remaining allocated balance (or just deallocates max amount).
2. However, if a user is in a loss, `maintaince margin` is **NOT** applied (ignored) and he is **NOT protected** from being almost immediately liquidatable if he opens with max margin and no remaining allocated balance (or just deallocates max amount).

User in a profit and user in a loss should be completely irrelevant from the risk standpoint. **Why** the user who is currently in a loss should **not be protected** from being almost immediately liquidatable? What is different from user who is in profit? Example (cva=lf=0, mm=100):

1. User A. Allocated balance = 50, open long 1 ETH at 100, current price of ETH = 150, unrealized profit = 50, locked balance = 100.
2. User B. Allocated balance = 250, open long 1 ETH at 300, current price of ETH = 150, unrealized loss = -150, locked balance = 100.

If users A and B close their positions, both will have allocated balance = 100 (User A: `50 + 50 = 100`, User B: `250 - 150 = 100`). So essentially both users are the same (including their open position), even though one of them is in a loss and the other one is in a profit. However:

1. User A can not deallocate anything and is thus protected from being quickly liquidated (he will only be liquidatable if his loss is -50)
2. But User B can deallocate 100 (ignoring `mm`). After deallocation he will be liquidatabale when the loss goes from -150 to -151, so a minimal additional loss will get him liquidated.
3. If, instead, User B closes positions, then re-opens them immediately again (allocated balance = 100, upnl = 0, locked balance = 100), he will not be able to deallocate again.

So why from 3 situations which are essentially the same, in situation 2. the user is allowed to ignore the `maintaince margin` and bring himself to almost liquidation?

To answer @MoonKnightDev post:
> Here's the thing about keeping a constant margin (mm) all the time. If we do this even when a user is losing, we'd be locking up a part of their balance for no big reason - just a safety margin. Honestly, that doesn't make much sense.

Why do you lock up a part of the balance of the user who is winning for no big reason? Honestly, please tell me what's different between a user who is winning and a user who is losing, if their allocated balance + upnl is the same? I don't get it. They're the same. They have absolutely the same positions, just different entry prices and different upnl, but the end result (balance + upnl) is the same, and any changes in prices will have the same effect for both of them.

> Now, the whole point of having a margin is to cover a user's losses after they've opened positions. So, when they're opening a position, we make sure they've got enough margin to prevent getting liquidated on the spot and offset some losses later on.

Right! So why do you ignore what you just stated for user who is currently in a loss? You allow him to open position without enough margin.

> If party A is taking big losses and still tries to open a new position, well, that means they're okay with the risk of liquidation. Even if it doesn't happen right away. And it's not a problem for party B. If party A gets liquidated, party B will still get their profit and CVA.

Ok. If party A is currently in a profit and tries to open a new position - why are you **not** okay with the risk of liquidation? (and apply `maintaince margin`) What's the difference? Get rid of that `margin maintance` if you're okay with the risk of liquidation.

> But for stuff like opening and closing positions, we use a different formula. That's because these actions have their own unique considerations. Like, when you're closing a position, you could potentially offset a loss with another position's mm. So, we've got to adjust the formula a bit. And when it comes to opening a position, you need enough free margin to get started.

But the user in a loss doesn't need enough free margin. I do think you have to think again of what's different between user who is in a loss and user who is in a profit. They can have the same positions, the same balance+upnl.

Sorry for the long escalation comment, but I wanted to give as much detail as possible into this issue, because I think that developers misundestand something about this issue and it's somewhat important even though it's medium. If you look at basically *all* the other derivatives protocols, *all* of them use the formula I suggest for a reason. It was a real surpise to see such strange bias for users with a loss and I honestly don't get it. User profit or loss is meaningless in isolation, what matters is the account value (balance + unrealized pnl).

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Let me get the facts straight on why the protocol needs `maintaince margin` (`mm`) at all: it is to prevent the user from being almost immediately liquidatable if he opens position at max leverage (`allocated balance = locked balance`). If there is no `maintaince margin` (`mm = 0`), then if `allocated balance = locked balance = cva + lf`, the position becomes liquidatable with any loss (so can become liquidatable almost immediately after being open). `Maintaince margin` aims to prevent it.
> 
> This issue is a valid medium, because `maintaince margin` is completely ignored when user account is in a big enough loss. So, let me state this again:
> 
> 1. If a user is in a profit, `maintaince margin` is applied and he is protected from being almost immediately liquidatable if he opens with max margin and no remaining allocated balance (or just deallocates max amount).
> 2. However, if a user is in a loss, `maintaince margin` is **NOT** applied (ignored) and he is **NOT protected** from being almost immediately liquidatable if he opens with max margin and no remaining allocated balance (or just deallocates max amount).
> 
> User in a profit and user in a loss should be completely irrelevant from the risk standpoint. **Why** the user who is currently in a loss should **not be protected** from being almost immediately liquidatable? What is different from user who is in profit? Example (cva=lf=0, mm=100):
> 
> 1. User A. Allocated balance = 50, open long 1 ETH at 100, current price of ETH = 150, unrealized profit = 50, locked balance = 100.
> 2. User B. Allocated balance = 250, open long 1 ETH at 300, current price of ETH = 150, unrealized loss = -150, locked balance = 100.
> 
> If users A and B close their positions, both will have allocated balance = 100 (User A: `50 + 50 = 100`, User B: `250 - 150 = 100`). So essentially both users are the same (including their open position), even though one of them is in a loss and the other one is in a profit. However:
> 
> 1. User A can not deallocate anything and is thus protected from being quickly liquidated (he will only be liquidatable if his loss is -50)
> 2. But User B can deallocate 100 (ignoring `mm`). After deallocation he will be liquidatabale when the loss goes from -150 to -151, so a minimal additional loss will get him liquidated.
> 3. If, instead, User B closes positions, then re-opens them immediately again (allocated balance = 100, upnl = 0, locked balance = 100), he will not be able to deallocate again.
> 
> So why from 3 situations which are essentially the same, in situation 2. the user is allowed to ignore the `maintaince margin` and bring himself to almost liquidation?
> 
> To answer @MoonKnightDev post:
> > Here's the thing about keeping a constant margin (mm) all the time. If we do this even when a user is losing, we'd be locking up a part of their balance for no big reason - just a safety margin. Honestly, that doesn't make much sense.
> 
> Why do you lock up a part of the balance of the user who is winning for no big reason? Honestly, please tell me what's different between a user who is winning and a user who is losing, if their allocated balance + upnl is the same? I don't get it. They're the same. They have absolutely the same positions, just different entry prices and different upnl, but the end result (balance + upnl) is the same, and any changes in prices will have the same effect for both of them.
> 
> > Now, the whole point of having a margin is to cover a user's losses after they've opened positions. So, when they're opening a position, we make sure they've got enough margin to prevent getting liquidated on the spot and offset some losses later on.
> 
> Right! So why do you ignore what you just stated for user who is currently in a loss? You allow him to open position without enough margin.
> 
> > If party A is taking big losses and still tries to open a new position, well, that means they're okay with the risk of liquidation. Even if it doesn't happen right away. And it's not a problem for party B. If party A gets liquidated, party B will still get their profit and CVA.
> 
> Ok. If party A is currently in a profit and tries to open a new position - why are you **not** okay with the risk of liquidation? (and apply `maintaince margin`) What's the difference? Get rid of that `margin maintance` if you're okay with the risk of liquidation.
> 
> > But for stuff like opening and closing positions, we use a different formula. That's because these actions have their own unique considerations. Like, when you're closing a position, you could potentially offset a loss with another position's mm. So, we've got to adjust the formula a bit. And when it comes to opening a position, you need enough free margin to get started.
> 
> But the user in a loss doesn't need enough free margin. I do think you have to think again of what's different between user who is in a loss and user who is in a profit. They can have the same positions, the same balance+upnl.
> 
> Sorry for the long escalation comment, but I wanted to give as much detail as possible into this issue, because I think that developers misundestand something about this issue and it's somewhat important even though it's medium. If you look at basically *all* the other derivatives protocols, *all* of them use the formula I suggest for a reason. It was a real surpise to see such strange bias for users with a loss and I honestly don't get it. User profit or loss is meaningless in isolation, what matters is the account value (balance + unrealized pnl).

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by panprog** [comment]
> It's a pretty neat system, especially since in a cross system, all those mm values are out in the open. So, one position's losses can be covered by everyone else's mm. This keeps liquidation risk low for everyone.

I'm not sure I understand this one correctly, but I don't think it's the case. For example:
PartyA has positions:
pos1: upnl = 100, mm = 50
pos2: upnl = -200, mm = 50
total: upnl = -100, mm = 100
partyA can deallocate up to balance of: 100
so partyA has balance (100) + upnl (-100) = 0 remaining balance so it's on the brink of liquidation.

PartyB has positions:
pos1: upnl = -100, mm = 50
pos2: upnl = 200, mm = 50
total: upnl = 100, mm = 100
partyB can deallocate up to balance of: 0
so partyB has balance (0) + upnl (+100) = 100 remaining balance, so it's far from being liquidated.

PartyA and PartyB are basically mirrored, so these positions can be actually between partyA and partyB.
Now 2 scenarios:
1. pos1 sharply falls from +100 profit to +50 profit for partyA (-50 for partyB), partyA becomes liquidatable. At this point partyA balance is 100, upnl -150; partyB balance is 0, upnl +150. However, since partyA only has balance of 100, partyB will only receive 100, not 150, losing funds due to bad debt.
2. pos2 sharply falls from +200 profit to +150 profit for partyB (-150 for partyA). Nothing happens, because partyA now has balance 100, upnl -50; partyB has balance 0, upnl +50, so both parties are solvent.

So exactly the same scenario, but the party which is currently in a loss has much higher risk of going into bad debt and causing the other side to lose funds due to this. On the other hand, the party which is currently in a profit has much smaller chance of going into bad debt, so the other side is more safe.

As you can see from the example, risk profile is different for party which is in a profit and party which is in a loss due to this strange formula which lets losing party ignore `mm`, meaning that losing parties create higher risk to the counterparties than they should.

**Comment by naveedinno** [comment]
> User A can not deallocate anything and is thus protected from being quickly liquidated (he will only be liquidatable if his loss is -50)

If I understand your example correctly, he can actually deallocate 50.

It seems you are heading to the 'else' statement in the partyAAvailableForQuote method even when the upnl is positive.

**Comment by panprog** [comment]
> 1. User A. Allocated balance = 50, open long 1 ETH at 100, current price of ETH = 150, unrealized profit = 50, locked balance = 100.

This is partyAAvailableForQuote:
```solidity
    function partyAAvailableForQuote(int256 upnl, address partyA) internal view returns (int256) {
        AccountStorage.Layout storage accountLayout = AccountStorage.layout();
        int256 available;
        if (upnl >= 0) {
            available =
                int256(accountLayout.allocatedBalances[partyA]) +
                upnl -
                int256(
                    (accountLayout.lockedBalances[partyA].total() +
                        accountLayout.pendingLockedBalances[partyA].total())
                );
```

available = 50 + 50 - 100 = 0

So User A can deallocate 0.

**Comment by naveedinno** [comment]
> * User A. Allocated balance = 50, open long 1 ETH at 100, current price of ETH = 150, unrealized profit = 50, locked balance = 100.
> 
> * User B. Allocated balance = 250, open long 1 ETH at 300, current price of ETH = 150, unrealized loss = -150, locked balance = 100.

The first user has already used their UPNL for an opening position, so they can't deallocate anything. We can only reach the state of User 1 if the user first opens a $50 position and then uses the $50 UPNL from that position to open another $50 position, resulting in a total MM of $100.

As for the second user, they are at a loss of -$150. To calculate the "availableForQuote" value, we cover $100 of this amount with their MM. The remaining $50 is covered by their free balance, leaving the user with $100 that they can deallocate.

**Comment by panprog** [comment]
> We can only reach the state of User 1 if the user first opens a $50 position and then uses the $50 UPNL from that position to open another $50 position, resulting in a total MM of $100.

He can also open with allocated balance of 100, then after he accumulated profit of $50 he can deallocate 50.

> As for the second user, they are at a loss of -$150. To calculate the "availableForQuote" value, we cover $100 of this amount with their MM. The remaining $50 is covered by their free balance, leaving the user with $100 that they can deallocate.

Oh wow, I see your logic. 

@Navid-Fkh, Do I understand you correctly that your intended `mm` usage is **NOT** preventing user from being almost immediately liquidatable after deallocations or new positions opened? It's just that normally this `mm` is used to prevent the user from accidently or intentionally putting him at the risk of liquidation, and currently protocol fails to achieve it due to the issue in this report.

From your description is appears that `mm` is used to loosely restrict total allocated balances in the protocol to be some percentage from total notional of opened positions? Is that correct? So that any position requires from `mm` to `2*mm` (depending on profit/loss of parties) of additional locked balance per notional of positions opened (and protocol doesn't care which parties provide it as long as the `mm` is provided)?

Although even if you don't care about letting user liquidate himself right after opening/deallocating, it's currently still unfair for users. For example, if `mm` is 1% off notional:
1. User A has `$1.010.000` allocated balance and `-$1.010.000` upnl and `10.000` locked balance. He is allowed to open a new position of `$100.000.000` without depositing any additional funds. So he will have such high position with 0 funds available (his allocated balance = unrealized loss).
2. But if he closes position, his allocated balance becomes 0. He can not open anything (he needs to deposit `$1.000.000` to open the same position).

On the other hand, partyB must care about unrealized loss of the partyA which requested the quote: partyA from point 1 (high unrealized loss) is more risky, because it has 0 funds to open the quote, while partyA from point 2 (no loss) is less riky, because it will have full `mm` available for the new quote.

Are you really OK with such asymmetric risk depending on unrealized loss? If you are OK with this, I don't really see why you need `mm` at all - any user (at least any partyA) can intentionally get into the unrealized loss to ignore `mm`, and if `mm` can be avoided if needed - why is it needed at all?

**Comment by naveedinno** [comment]
I'm sorry, but I'm not entirely sure I understand your point, or perhaps there's a misunderstanding on our end. Let's take a moment to clarify our definition of "MM":

As stated in the readme file, "MM" refers to the amount that backs a position and is taken into consideration when the position is at risk of liquidation. This can be broken down into two distinct scenarios:

1. When the position is in profit: The MM is locked and acts as a safety margin for the position. This means it's not available for the user to use this amount to open another position.

 2. When the position is at a loss: Here, the loss is deducted from the MM, demonstrating the true utility of MM for the user. Should the loss exceed the MM, the user's free balance will be drawn upon to cover the excess loss.

In essence, MM ensures that users set aside funds to account for potential losses from their position. This precautionary measure prevents immediate liquidation and can offset a portion of their losses. Moreover, we regard MM in the same way as users' free balances, meaning there's no distinction between the two in liquidation calculations.

**Comment by panprog** [comment]
> In essence, MM ensures that users set aside funds to account for potential losses from their position

I want to clarify that since mm is only applied when opening new position or deallocating, these funds set aside are for new positions (or to keep existing positions safe when deallocating). 

> This precautionary measure prevents immediate liquidation and can offset a portion of their losses

Currently the protocol fails to achieve this: a user in a loss can open new position and be immediately liquidated because new position doesn't enforce "new" MM and allows to open new position without depositing additional funds to cover it.

Look at it from the following perspective: when new position is opened, does the user have enough funds to offset some potential losses from this new position?
1. User in profit or no loss. Forced to have or deposit new position MM. For example, balance = 50, upnl = 5, current locked mm = 50, additional position mm = 50. User is required to deposit 45 to be able to open such position. (50+5-50-50 +45 = 0)
2. User in a large loss. Ignores MM for new positions. For example, balance = 250, upnl = -250. Additional position mm = 50. Current mm locked: 50. User doesn't need to deposit anything to open such position. 

User 1 needs to deposit additional funds to cover new position mm, user 2 can open new position without any additional funds and since his balance = upnl, he can become liquidatable immediately. This means user 2 doesn't have to have any funds to offset future losses. So your stated goal fails for this user. 

Since protocol fails to achieve stated goal for mm and allows user to open more risky positions than he should, I think this should be valid medium.

**Comment by naveedinno** [comment]
> 2\. User in a large loss. Ignores MM for new positions. For example, balance = 250, upnl = -250. Additional position mm = 50. Current mm locked: 50. User doesn't need to deposit anything to open such position.

250 - 250 - 50 != 0

User still needs to deposit

**Comment by panprog** [comment]
> 250 - 250 - 50 != 0
> 
> User still needs to deposit

Allocate 50, open position, deallocate 50 - this is the same as opening without allocating. 

~~~solidity
            int256 mm = int256(accountLayout.lockedBalances[partyA].mm);
            int256 considering_mm = -upnl > mm ? -upnl : mm;
            available =
                int256(accountLayout.allocatedBalances[partyA]) -
                int256(
                    (accountLayout.lockedBalances[partyA].cva +
                        accountLayout.lockedBalances[partyA].lf +
                        accountLayout.pendingLockedBalances[partyA].total())
                ) -
                considering_mm;
~~~

When deallocating:
mm = 100
considering_mm = 250
available = 250 - 0 - 250 = 0

So deallocation is allowed up to allocated balance = -upnl

**Comment by naveedinno** [comment]
> So deallocation is allowed up to allocated balance = -upnl

what do you mean by this? you are saying that user can deallocate 250?!!

**Comment by panprog** [comment]
> what do you mean by this? you are saying that user can deallocate 250?!!

No, he deposits 50, opens position, deallocates 50. He now has still 250 allocated, -250 upnl and new position opened (locked balance now 100)

**Comment by naveedinno** [comment]
> > what do you mean by this? you are saying that user can deallocate 250?!!
> 
> No, he deposits 50, opens position, deallocates 50. He now has still 250 allocated, -250 upnl and new position opened (locked balance now 100)

But he can't deallocate the 50 !

**Comment by panprog** [comment]
> But he can't deallocate the 50 !

He can! That's what this issue is about. Check [previous comment](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/148#issuecomment-1690029303) or POC in issue itself.

After allocating 50 and opening new position he has:
allocatedBalance = 300
upnl = -250
locked mm = 100

now calculating `partyAAvailableForQuote`
https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/libraries/LibAccount.sol#L42-L51
mm = 100
considering_mm = 250 > 100 ? 250 : 100 = 250
available = 300 - 0 - 250 = 50 -- this is available for deallocating, so he can deallocate 50.
After deallocation:
allocatedBalance = 250
upnl = -250
locked mm = 100

**Comment by shaka0x** [comment]
> > If party A is taking big losses and still tries to open a new position, well, that means they're okay with the risk of liquidation. Even if it doesn't happen right away. And it's not a problem for party B. If party A gets liquidated, party B will still get their profit and CVA.
> 
> Ok. If party A is currently in a profit and tries to open a new position - why are you **not** okay with the risk of liquidation? (and apply `maintaince margin`) What's the difference? Get rid of that `margin maintance` if you're okay with the risk of liquidation.

The MM avoids a user to be instantly liquidated because they did not realized of it. A user that is in a loss and keeps opening positions does know they are in risk of liquidation. In fact, in your impact you are talking explicitly about a `Malicious partyA`.

The MM is meant to cover a loss until that value is reached, it is its intended behaviour.

**Comment by panprog** [comment]
After further discussion I agree that this is intentional and by-design, the issue can be closed as low/invalid due to misunderstanding of the intended MM behavior.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this a low issue as it is intended design based on the comments above and further discussion

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [panprog](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/148/#issuecomment-1654671934): rejected
