### ISSUE TITLE
mstpr-brainbot - partyB can dodge liquidation if partyA gets liquidated first

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#158]
mstpr-brainbot

high

# partyB can dodge liquidation if partyA gets liquidated first

## Summary
partyA liquidation will save the partyB's liquidation status.
## Vulnerability Detail
In the event that both partyA and partyB are eligible for liquidation and linked via quotes, the liquidation of partyA will inherently trigger the liquidation process for partyB. As partyA undergoes liquidation, all associated quotes are effectively closed and finalized. As a consequence of this chain reaction, partyB effectively sidesteps its impending liquidation.

## Impact
Since partyA can have multiple quotes with different partyB's, partyA can get liquidated easier than a partyB in general. Also, if one of the positions of partyB can be liquidated it would mean the counterparty A is winning, however, that doesn't mean that the partyA is also liquidatable. 
## Code Snippet
https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L20-L383
## Tool used

Manual Review

**Comment by mstpr** [comment]
Escalate

This issue is valid because the above scenario is definitely not an intended behaviour. PartyA can have many trades going on with different partyB's which means that a partyA can be liquidatable in the same time with one of its partyB's. In this case, if partyA gets liquidated first the partyB will not be liquidated.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This issue is valid because the above scenario is definitely not an intended behaviour. PartyA can have many trades going on with different partyB's which means that a partyA can be liquidatable in the same time with one of its partyB's. In this case, if partyA gets liquidated first the partyB will not be liquidated. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
> In this case, if partyA gets liquidated first the partyB will not be liquidated.

I would have to ask more details and prove than the original report present before bringing for sponsor review.

**Comment by mstpr** [comment]
@ctf-sec 

I think it's kind of straightforward. 

First, we agree that both partyA and partyB can be liquidatable in same time.
Example:
PartyA has 5 trades going on with 5 partyB's. 4 of those trades are in loss for partyA and 1 of it in profit. Overall balance of partyA is liquidatable. That partyB that has losses with this partyA is also liquidatable. 

Now, if partyA will be liquidated before the partyB, partyB will dodge its liquidation because once the partyA is liquidated its balances reset to 0 and all the quotes are closed so partyB does not have this quote anymore in its sheet.

**Comment by hrishibhat** [comment]
Sponsor comment:
> Regarding issue #158, that is the intended behavior.

**Comment by mstpr** [comment]
I am not sure if this should be an intended behaviour tho, 
say partyA has 5 trades with 5 partyB's. 

Say partyA has total of 5000 locked balance where 3000 of it is mm and remaining 2000 is cva+lf across all trades he has with 5 partyB. Also, say that the overall pnl for partyA is -3001. Now, if we calculate the partyA balance for liquidation according to code:
5000(locked balances) - 2000 (cva+lf) - 3001 (pnl) = -1, which means partyA is liquidatable. 

Let's say one trade that partyA has with one partyB is as follows:
1000 mm, 900 cva, 100 lf. 
say the pnl for partyA for this trade is +1005, which means -1005 for the partyB. 
partyB is liquidatable according to the formula
2000 - 1000 - 1005 = -5, which means partyB is liquidatable. 

Now, say partyA gets liquidated first. The pnl was -1005 and cva was 900 for the partyB. 
partyBLockedBalances = 1000 + 900 + 100 = 2000
-1005 will be deducted from partyB and 900 (cva) will be credited to partyB after partyA's liquidation. 
Hence the final locked balances of partyB will be: 
2000 - 1005 (pnl) + 900 (cva) = 1895. PartyB has 1895 locked balances that can be withdrawable any time. 

Now, what if the partyB would get liquidated first ?

if partyB would've liquidated first then the partyA would get the pnl + cva, pnl was already accounted when partyA's liquidation level calculated however the cva that partyA will get from this specific trade was not accounted. This cva might make partyA solvent again. Let's calculate

partyA locked balances was 5000 where 2000 of it was cva+lf and 3000 was the mm. Now, when partyB gets liquidated partyA will get the pnl + cva, which is 1005(pnl) + 900(cva) to its locked balances.

Now, since the +1005 pnl realized now the total pnl of partyA is -4006, let's calculate the liquidation level accordingly:
6905(locked balances prev + liq pnl + cva) - 2000 - 4006 =  899, which means partyA is not liquidatable anymore because of the cva it get from the liquidated partyB.

As seen, whoever gets liquidated first it will help the other party. In partyA case, it is ok that partyB gets liquidated, because they are directly linked to each other and it would be the correct choice if partyB would get liquidated first. However, when partyA gets liquidated when the partyB was also liquidatable, partyB gets an advantage as seen in the example above. Instead of having 0 locked balances, partyB ended up with 1895, only -105 loss from its initial balance, which is huge and only reason why that happens was the unfortunate liquidation of partyA.

**Comment by panprog** [comment]
> Now, since the +1005 pnl realized now the total pnl of partyA is -4006, let's calculate the liquidation level accordingly:
> 6905(locked balances prev + liq pnl + cva) - 2000 - 4006 = 899

partyA will also have locked balances (cva+lf=1000) from quote with partyB released, so the correct formula will be
6905 - 1000 - 4006 = 1899 - roughtly the same balance partyB has if partyA is liquidated first.

When both parties are liquidatable, the one who gets liquidated first will always save the other party from liquidation due to cva, but they're in the same position: neither party is "more fair" to be liquidated first. The protocol doesn't specify the order or special resolution for such case, so I believe that it's just the luck of one party if the other is liquidated first, I don't see any issue there: each party is subject to liquidation if it becomes liquidatable at any time. However, protocol can't guarantee the liquidation, so if some party is not liquidated and becomes solvent again, then it's just luck.

**Comment by mstpr** [comment]
If partyB gets liquidated first, this is the right thing. PartyB is directly responsible of the health of this trade. CVA should be sent to partyA because the liquidation cause of partyB is the trade that it has with partyA.

However, if partyA gets liquidated first then partyB should not receive CVA because the liquidation cause of partyA is not because this partyB but overall all trades it has.

**Comment by naveedinno** [comment]
I discussed this with the team, and it is the intended behavior in an asymmetric system! PartyB will dodge liquidation and get the CVA even when they are themselves liquidatable.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this a valid low based on the above comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [mstpr](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/158/#issuecomment-1652029042): accepted
