### ISSUE TITLE
shaka - Party A can be liquidated with outdated price data

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#188]
shaka

medium

# Party A can be liquidated with outdated price data

## Summary

Party A can be liquidated with outdated price data.

## Vulnerability Detail

`LiquidationFacetImpl.liquidatePositionsPartyA` does not update the nonce of party A after the liquidation process is completed.

This can be used for a malicious liquidator to perform a "griefing" attack on party A, by using outdated uPnL data to initiate a new liquidation process.

The sequence of events would be the following:

1. Party A is in the process of liquidation. The liquidator requests off-chain for a uPnL signature for party A, that will reflect the insolvency of party A.
2. The liquidator calls `liquidatePositionsPartyA` to complete the liquidation process of party A. Now party A is not insolvent anymore.
3. The liquidator uses the uPnL signature from step 1 to initiate a new liquidation process of party A, by calling `liquidatePartyA`. The uPnL signature is valid, because the nonce of party A has not been updated and its timestamp is recent enough. However, this uPnL will reflect the insolvency of party A before the liquidation process of step 2 was completed, instead of the current state of party A.

Although there is no direct economic loss for party A, this can be used to grief party A by locking the account until the liquidation process is completed.

## Impact

A malicious liquidator can grief party A by locking the account until the liquidation process is completed.

## Code Snippet

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L23

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/libraries/LibMuon.sol#L87-L106

## Tool used

Manual Review

## Recommendation

Increment the nonce of party A after the liquidation process is completed.

Duplicate of #190

**Comment by shaka0x** [comment]
Escalate.

The issue has been marked incorrectly as a duplicate of #113. The mentioned issue is about a problem with the validation of the **price signature in the `setSymbolsPrice` function**, which is executed once the liquidation process has started.

This issue is completely different, as points out how the the liquidation process can be incorrectly **started** due to a problem with the validation of the **UPNL signature in the `liquidatePartyA` function**.

**Comment by sherlock-admin2** [comment]
> Escalate.
> 
> The issue has been marked incorrectly as a duplicate of #113. The mentioned issue is about a problem with the validation of the **price signature in the `setSymbolsPrice` function**, which is executed once the liquidation process has started.
> 
> This issue is completely different, as points out how the the liquidation process can be incorrectly **started** due to a problem with the validation of the **UPNL signature in the `liquidatePartyA` function**.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
duplicate of https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/232

**Comment by shaka0x** [comment]
> duplicate of #232

Reading #232 I don't see it as a duplicate. Also, I think could have explained it better in my escalation.

My issue describes that 1) **`liquidatePositionsPartyA`** does not update the nonce and this cause that 2) outdated uPnL signature is submitted to **`liquidatePartyA`**.

#232 describes that 1) **`liquidatePartyA` and `liquidatePartyB`** do not update the nonce and this can cause that 2) outdated uPnL signature is submitted to other functions. There is no mention to `liquidatePositionsPartyA` not updating the nonce. That is where I see the problem, as after calling that function the real uPnL does change (partyA recovers solvency) and that fact is not reflected in the old uPnL signature, that is now not representing the current state of partyA. I do not see any issue in **`liquidatePartyA` and `liquidatePartyB`** not updating the nonce, as there is no movement of funds there, so uPnL signature still represents the current state of the parties.

**Comment by panprog** [comment]
#232 is a family of issues describing lack of nonce update in all liquidation functions. While #232 itself only mentions liquidatePartyA and liquidatePartyB, the other duplicates of it mention the other functions as well. In particular, my own  dup (#190) mentions all of the liquidate functions:

> Nonce for neither partyA nor partyB is increased in any of the `LiquidationFacetImpl` functions.
...
> at the very least nonce should be increased in the following functions:
> 
> 1. `liquidatePartyA`. Increase nonce for partyA
> 2. `liquidatePendingPositionsPartyA`. Increase nonce for partyA and for all corresponding partyBs (because pending quotes are liquidated, freeing up locked balance, which is a state changing action)
> 3. `liquidatePositionsPartyA`. Increase nonce for partyA and for all corresponding partyBs (because partyB allocatedBalance and upnl are changed and open position is liquidated)
> 4. `liquidatePartyB`. Increase nonce for partyA and partyB (because allocatedBalance for both parties changes).
> 5. `liquidatePositionsPartyB`. Increase nonce for partyA and partyB (because positions are deleted)

The root cause is the same as in #232, so it should be duplicate of it

**Comment by shaka0x** [comment]
> #232 is a family of issues describing lack of nonce update in all liquidation functions. While #232 itself only mentions liquidatePartyA and liquidatePartyB, the other duplicates of it mention the other functions as well. In particular, my own dup (#190) mentions all of the liquidate functions:
> 
> > Nonce for neither partyA nor partyB is increased in any of the `LiquidationFacetImpl` functions.
> > ...
> > at the very least nonce should be increased in the following functions:
> > 
> > 1. `liquidatePartyA`. Increase nonce for partyA
> > 2. `liquidatePendingPositionsPartyA`. Increase nonce for partyA and for all corresponding partyBs (because pending quotes are liquidated, freeing up locked balance, which is a state changing action)
> > 3. `liquidatePositionsPartyA`. Increase nonce for partyA and for all corresponding partyBs (because partyB allocatedBalance and upnl are changed and open position is liquidated)
> > 4. `liquidatePartyB`. Increase nonce for partyA and partyB (because allocatedBalance for both parties changes).
> > 5. `liquidatePositionsPartyB`. Increase nonce for partyA and partyB (because positions are deleted)
> 
> The root cause is the same as in #232, so it should be duplicate of it

Although #232 describes an issue related with the lack of nonce updates in liquidations, the scenario described is totally different and tn does not even involve the same functions. What is more important, the impact is different to the one described in this issue and has been escalated. I also consider the impact described in #232 as invalid, while the scenario and impact of this issue as valid. If other issues have been incorrectly marked as duplicates of #232 because they describe different scenarios they should have also been escalated.

I asked for some concerns about these cases in the [Discord channel](https://discord.com/channels/812037309376495636/849665750469836810/1115019941620498522) and this was the response:

> Two issues shouldn't be duplicated together in the first place unless they're describing the same vulnerability. So if one gets invalidated, the others should as well. If the others should be valid while the best-report should be invalid, that means they were duplicated together improperly

**Comment by panprog** [comment]
> Although #232 describes an issue related with the lack of nonce updates in liquidations, the scenario described is totally different and tn does not even involve the same functions.

Please refer to Sherlock [judging duplication rules](https://docs.sherlock.xyz/audits/judging/judging#duplication-rules):
> Issues identifying a core vulnerability can be considered duplicates. 
Scenario 1:
There is a root cause/error/vulnerability A in the code. This vulnerability A -> leads to two attacks paths:
> - B -> high severity path
> - C -> medium severity attack path/just identifying the vulnerability.
> Both B & C would not have been possible if error A did not exist in the first place. In this case, both B & C should be put together as duplicates.
> - In addition to this, there is a submission D which identifies the core issue but does not clearly describe the impact or an attack path. Then D is considered low. 

#232 and its duplicates (including this one) identify the root cause A (lack of nonce update in all liquidation functions). All of them also identify the impact as signature replay, which I think is high severity by itself. Then, some reports also provide different scenarios (attack paths), demonstrating medium or high impact (#232 doesn't provide any scenario, just mentions functions where it can be reused, without any exact scenario). This issue also provides a different scenario, but the root cause is still the same, and the impact (signature replay) in my opinion is the same. So all of them are correct duplicates.

I can only see the grounds for escalation if signature replay by itself is not high severity. Then yes, different scenarios will lead to different severity attacks and all duplicates should remain duplicate, but severity of all of them should be adjusted (some high, some low, some medium). But I don't think this should be the case.

**Comment by shaka0x** [comment]
> > Although #232 describes an issue related with the lack of nonce updates in liquidations, the scenario described is totally different and tn does not even involve the same functions.
> 
> Please refer to Sherlock [judging duplication rules](https://docs.sherlock.xyz/audits/judging/judging#duplication-rules):
> 
> > Issues identifying a core vulnerability can be considered duplicates.
> > Scenario 1:
> > There is a root cause/error/vulnerability A in the code. This vulnerability A -> leads to two attacks paths:
> > 
> > * B -> high severity path
> > * C -> medium severity attack path/just identifying the vulnerability.
> >   Both B & C would not have been possible if error A did not exist in the first place. In this case, both B & C should be put together as duplicates.
> > * In addition to this, there is a submission D which identifies the core issue but does not clearly describe the impact or an attack path. Then D is considered low.
> 
> #232 and its duplicates (including this one) identify the root cause A (lack of nonce update in all liquidation functions). All of them also identify the impact as signature replay, which I think is high severity by itself. Then, some reports also provide different scenarios (attack paths), demonstrating medium or high impact (#232 doesn't provide any scenario, just mentions functions where it can be reused, without any exact scenario). This issue also provides a different scenario, but the root cause is still the same, and the impact (signature replay) in my opinion is the same. So all of them are correct duplicates.
> 
> I can only see the grounds for escalation if signature replay by itself is not high severity. Then yes, different scenarios will lead to different severity attacks and all duplicates should remain duplicate, but severity of all of them should be adjusted (some high, some low, some medium). But I don't think this should be the case.

If you keep reading the judging duplication rules:

> In case the same vulnerability appears across multiple places in different contracts, they can be considered duplicates. 
The exception to this would be if underlying code implementations, impact, and the fixes are different, then they can be treated separately. 

And this is the case:
1) The issue affects to different parts of the code. #232 highlights a supposed vulnerability in `liquidatePartyA` and `liquidatePartyB` while this issue identifies a vulnerability in `liquidatePositionsPartyA`.
2) The impact is different: in #232 the replayed signature would happen with no change in the real uPnL value, while this issue describes a scenario where a signature can be replayed involving the use of an updated uPnL.
3) The proposed fix is different: #232 proposes incrementing the nonce when the liquidation process starts, which I do not consider necessary, while this issue proposes incrementing the nonce after the liquidation process is completed, as it is when the change in the uPnL is produced.

**Comment by panprog** [comment]
> The exception to this would be if underlying code implementations, impact, and the fixes are different, then they can be treated separately.

I don't think this issue falls in the exception:
1. Underlying code implementation is exactly the same for all: lack of nonce increase in all liquidation functions. Yes, different duplicates mention different exact functions, but they're all related and in the same contract. The core issue is the same in all of them, so I don't think it makes sense for `liquidatePartyA` and `liquidatePositionsPartyA` lack of nonce increase to be considered as different issues: they're the same, same reason, same fix. My report mentions **ALL** 6 functions in `LiquidationFacetImpl`: so do you think my report should count as 6 different issues? It doesn't make sense. Maybe it makes more sense to make my report the main one as it identifies all functions and also identifies the most critical impact (theft of all protocol funds), then all the others are just dups which are not as complete. But it's really no big deal since the core reason and the fix are obvious.
2. Fixes: increase nonce in **ALL** liquidation functions. Again, not all duplicates and #232 itself mention all functions, but it should be pretty obvious that nonce increase is required in all liquidation functions, not just start or end of liquidation. And again, since all these functions are in the same contract and are all related, I think that saying that fix to add nonce increase to `liquidatePartyA` and the fix to add nonce increase to `liquidatePositionsPartyA` are different fixes is incorrect: the fix is the same.
4. Impact migth be not so obvious, so it can be treated as high for all (signature replay) or different impacts depending on actual funds loss demonstrated.

So only impact is in question. But the exception requires all 3 (underlying code, impact and fixes) to be different. So I think that scenario 1 from the duplication rules is applicable: all these issues are duplicates, but maybe the impact is different.

I think our arguments are clear, let's leave it up to Sherlock to decide here.

**Comment by shaka0x** [comment]
To put it simple is as if issue A highlights that function A has no reentrance protection while that in reality does not suppose any real damage for the protocol. While issue B highlights that function B has no reentrance protection and describes how this will impact the protocol. Just because both issues are about lack of reentrance protection and the code is in the same contract, that does not mean that they should be considered as duplicates.

So yes, at this point it is up to Sherlock to decide.

**Comment by hrishibhat** [comment]
Result:
High
Duplicate of #232 
While both arguments have their strong points, I agree with the @panprog's reasoning here:
https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/188#issuecomment-1672884866

the re-entrance example is a generic vulnerability that may not apply here, also issue #232 may not describe the attacks as its duplicates, the underlying issue is still the same from the code implementation POV. 

Additionally, Will make a note on improving the docs on duplication rules for such cases.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [shaka0x](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/188/#issuecomment-1653972514): accepted
