### ISSUE TITLE
xiaoming90 - Unrealized profit and loss (uPnL) signature (`upnlSig`) can be re-used and replayed as nonce is not incremented

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#232]
xiaoming90

high

# Unrealized profit and loss (uPnL) signature (`upnlSig`) can be re-used and replayed as nonce is not incremented

## Summary

The unrealized profit and loss (uPnL) signature (`upnlSig`) can be re-used and replayed as nonce is not incremented within the `LiquidationFacetImpl.liquidatePartyA` and `LiquidationFacetImpl.liquidatePartyB` functions.

## Vulnerability Detail

Both the `LiquidationFacetImpl.liquidatePartyA` and `LiquidationFacetImpl.liquidatePartyB` functions accept an unrealized profit and loss (uPnL) signature (`upnlSig`) and utilize it to compute the available balance of PartyA or PartyB

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L20

```solidity
File: LiquidationFacetImpl.sol
20:     function liquidatePartyA(address partyA, SingleUpnlSig memory upnlSig) internal {
21:         MAStorage.Layout storage maLayout = MAStorage.layout();
22: 
23:         LibMuon.verifyPartyAUpnl(upnlSig, partyA);
24:         int256 availableBalance = LibAccount.partyAAvailableBalanceForLiquidation(
25:             upnlSig.upnl,
26:             partyA
27:         );
28:         require(availableBalance < 0, "LiquidationFacet: PartyA is solvent");
29:         maLayout.liquidationStatus[partyA] = true;
30:         maLayout.liquidationTimestamp[partyA] = upnlSig.timestamp;
31:         AccountStorage.layout().liquidators[partyA].push(msg.sender);
32:     }
```

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L240

```solidity
File: LiquidationFacetImpl.sol
240:     function liquidatePartyB(
241:         address partyB,
242:         address partyA,
243:         SingleUpnlSig memory upnlSig
244:     ) internal {
..SNIP..
249:         LibMuon.verifyPartyBUpnl(upnlSig, partyB, partyA);
250:         int256 availableBalance = LibAccount.partyBAvailableBalanceForLiquidation(
251:             upnlSig.upnl,
252:             partyB,
253:             partyA
254:         );
..SNIP..
```

However, after using an unrealized profit and loss (uPnL) signature (`upnlSig`), it does not increment the nonce at the end of the function. As a result, the same unrealized profit and loss (uPnL) signature (`upnlSig`) can be reused in other functions that accept an unrealized profit and loss (uPnL) signature (`upnlSig`).

The unrealized profit and loss (uPnL) signature (`upnlSig`) of `liquidatePartyA` function can be re-used in the following functions:

- `AccountFacet.deallocate`

The unrealized profit and loss (uPnL) signature (`upnlSig`) of `liquidatePartyB` function can be re-used in the following functions:

- `AccountFacet.transferAllocation`
- `AccountFacet.deallocateForPartyB`
- `PartyBFacetImpl.lockQuote`

All four (4) functions above (`AccountFacet.deallocate`. `AccountFacet.transferAllocation`, `AccountFacet.deallocateForPartyB`, `PartyBFacetImpl.lockQuote`)  increment the nonce after using the signature. However, this was not done in the `LiquidationFacetImpl.liquidatePartyA` and `LiquidationFacetImpl.liquidatePartyB` functions.

## Impact

The same unrealized profit and loss (uPnL) signature (`upnlSig`) can be re-used and replayed across multiple functions. If the uPnL in an old signature gives an advantage (e.g. more profit) to the users compared to a newly generated signature, malicious users could cherry-pick and replay/submit the old signatures to the system. Since this is a zero-sum game, the gain of a user will be the loss of another user. The victim will end up losing more than expected.

In addition, once the first liquidation is completed, the signature can also be used to initiate the liquidation of the same party for a second time as long as the signature has not expired yet. If the liquidated party quickly injects funds and purchases more positions before the signature expires, the second liquidation might cause their new assets to be liquidated again.

## Code Snippet

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L20

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/liquidation/LiquidationFacetImpl.sol#L240

## Tool used

Manual Review

## Recommendation

Consider incrementing the nonce within the `liquidatePartyA` and `liquidatePartyB` so that the signature cannot be re-used or replayed.

```diff
function liquidatePartyA(address partyA, SingleUpnlSig memory upnlSig) internal {
    MAStorage.Layout storage maLayout = MAStorage.layout();

    LibMuon.verifyPartyAUpnl(upnlSig, partyA);
    int256 availableBalance = LibAccount.partyAAvailableBalanceForLiquidation(
        upnlSig.upnl,
        partyA
    );
    require(availableBalance < 0, "LiquidationFacet: PartyA is solvent");
    maLayout.liquidationStatus[partyA] = true;
    maLayout.liquidationTimestamp[partyA] = upnlSig.timestamp;
    AccountStorage.layout().liquidators[partyA].push(msg.sender);
+   accountLayout.partyANonces[msg.sender] += 1;
}
```

```diff
function liquidatePartyB(
    address partyB,
    address partyA,
    SingleUpnlSig memory upnlSig
) internal {
    AccountStorage.Layout storage accountLayout = AccountStorage.layout();
    MAStorage.Layout storage maLayout = MAStorage.layout();
    QuoteStorage.Layout storage quoteLayout = QuoteStorage.layout();

    LibMuon.verifyPartyBUpnl(upnlSig, partyB, partyA);
    int256 availableBalance = LibAccount.partyBAvailableBalanceForLiquidation(
        upnlSig.upnl,
        partyB,
        partyA
    );
+	accountLayout.partyBNonces[partyB][partyA] += 1;
	..SNIP..
}
```

Duplicate of #190

**Comment by mstpr** [comment]
Escalate

This is also invalid. When an account is liquidated if that's a partyA he needs to use sendQuote to create a quote to be liquidated which increments the nonce. 

If its a partyB when opens a position it also increments the nonce.

When an account is liquidated its balance is reset to "0".  None of the above functions requires a pnl.

"In addition, once the first liquidation is completed, the signature can also be used to initiate the liquidation of the same party for a second time as long as the signature has not expired yet. If the liquidated party quickly injects funds and purchases more positions before the signature expires, the second liquidation might cause their new assets to be liquidated again." This is also wrong because the nonce will increment in opening a position hence the signature will not be replayed. 

transferAllocation --> can't be used because the freshly liquidated account has no allocated balance
deallocate --> can't be used because the freshly liquidated account has no allocated balance
deallocateForPartyB --> can't be used because the freshly liquidated account has no allocated balance
lockQuote --> can't be used because the freshly liquidated account has no allocated balance

everything in the issue is invalid.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is also invalid. When an account is liquidated if that's a partyA he needs to use sendQuote to create a quote to be liquidated which increments the nonce. 
> 
> If its a partyB when opens a position it also increments the nonce.
> 
> When an account is liquidated its balance is reset to "0".  None of the above functions requires a pnl.
> 
> "In addition, once the first liquidation is completed, the signature can also be used to initiate the liquidation of the same party for a second time as long as the signature has not expired yet. If the liquidated party quickly injects funds and purchases more positions before the signature expires, the second liquidation might cause their new assets to be liquidated again." This is also wrong because the nonce will increment in opening a position hence the signature will not be replayed. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
@xiaoming9090

**Comment by xiaoming9090** [comment]
@ctf-sec 

This is a valid issue. The root cause is that the nonce is not incremented, which results in the classic signature replaying issue. This has been also raised by many other Watson. You may refer to the duplicate reports for additional references.

**Comment by hrishibhat** [comment]
@mstpr

**Comment by mstpr** [comment]
@hrishibhat this and all the other issues are invalid. As stated in the first escalation, once an account is liquidated it needs to perform other actions which will eventually increment the nonce. As again, this issue is completely wrong on all of its points.

**Comment by mstpr** [comment]
> @ctf-sec
> 
> This is a valid issue. The root cause is that the nonce is not incremented, which results in the classic signature replaying issue. This has been also raised by many other Watson. You may refer to the duplicate reports for additional references.

there is no "root cause" because the finding is invalid. Please give me example of the above issue you described in the issue.

**Comment by panprog** [comment]
> there is no "root cause" because the finding is invalid. Please give me example of the above issue you described in the issue.

While this report doesn't provide exact scenario when it's possible to exploit signature reuse, some duplicates of it do, for example check my #190 which shows a scenario to steal all protocol funds.

Basically, you assume that if partyA is liquidated and its allocated balances are 0, it can not do anything even if it can reuse the upnl signature. However, in this case partyB can still do actions and its allocated balance is not 0, so this can be abused by partyB. The same is also true if partyB is liquidated - partyA can reuse the signature and it still has allocated balance.

I don't think any other duplicate of this issue came up with a high impact scenario, however I believe that signature reuse is of high severity by itself (even if not possible to use now, it's always a very high possible impact in the future when introducing new features), so it's enough to show that the signature can be reused.

**Comment by shaka0x** [comment]
> I believe that signature reuse is of high severity by itself (even if not possible to use now, it's always a very high possible impact in the future when introducing new features), so it's enough to show that the signature can be reused.

According to Sherlock judging docs:

> Issues that result out of a future integration/implementation that was not intended (mentioned in the docs/README) or because of a future change in the code (as a fix to another issue) are not valid issues.

Also, the uPnL data sent by the liquidator to start the liquidation process should still be valid after the process is initiated, as it does not make any change in the accounting of the user being liquidated.

**Comment by mstpr** [comment]
@panprog 
To be honest I mainly reviewed this issue since this is picked as the "best" of the issue and its duplicates. There is no doubt that this issue is invalid. 

Looking for your issue, yes there is an exploit that could be resolved by incrementing nonce. However, obtaining 3 roles makes the severity lower imo. I think your issue should be counted as medium or low since you pointed out a real vulnerability in your finding. I think all the duplicates should be checked throughout and reclassified

**Comment by panprog** [comment]
> I think all the duplicates should be checked throughout and reclassified

I think I'm convinced by your (and @shaka0x) arguments that signature reuse itself is not high and a viable real impact scenario must also be presented. I agree with you that all duplicates should be checked and re-classified. Let's leave it up to Sherlock.

**Comment by MoonKnightDev** [comment]
Fixed code PR link:
https://github.com/SYMM-IO/symmio-core/pull/15

**Comment by hrishibhat** [comment]
Result:
High
Duplicate of #190 
After further consideration and discussion, given the complexity of the implementation the underlying issue of the non incrementing nonce, this issue and its duplicates are considered valid. And since #190 best describes the scenario under which this can be possibly exploited, considered this issue a valid high. Marking #190 as the main issue and the others its duplicate.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [mstpr](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/232/#issuecomment-1655382934): accepted
