### ISSUE TITLE
xiaoming90 - Leverage for market orders might deviate

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#246]
xiaoming90

medium

# Leverage for market orders might deviate

## Summary

The leverage for market orders might deviate as the locked values are not adjusted according to the change in the market price, resulting in unexpected losses.

## Vulnerability Detail

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyB/PartyBFacetImpl.sol#L112

```solidity
File: PartyBFacetImpl.sol
112:     function openPosition(
113:         uint256 quoteId,
114:         uint256 filledAmount,
115:         uint256 openedPrice,
116:         PairUpnlAndPriceSig memory upnlSig
117:     ) internal returns (uint256 currentId) {
..SNIP..
136:         if (quote.positionType == PositionType.LONG) {
137:             require(
138:                 openedPrice <= quote.requestedOpenPrice,
139:                 "PartyBFacet: Opened price isn't valid"
140:             );
141:         } else {
142:             require(
143:                 openedPrice >= quote.requestedOpenPrice,
144:                 "PartyBFacet: Opened price isn't valid"
145:             );
146:         }
..SNIP..
158:         if (quote.quantity == filledAmount) {
159:             accountLayout.pendingLockedBalances[quote.partyA].subQuote(quote);
160:             accountLayout.partyBPendingLockedBalances[quote.partyB][quote.partyA].subQuote(quote);
161: 
162:             if (quote.orderType == OrderType.LIMIT) {
163:                 quote.lockedValues.mul(openedPrice).div(quote.requestedOpenPrice);
164:             }
```

The leverage of a position is computed based on the following formula.

$leverage = \frac{price \times quantity}{lockedValues.total()}$

When opening a position, there is a possibility that the leverage might change because the locked values and quantity are fixed, but it could get filled with a different market price compared to the one at the moment the user requested.

To ensure that a fixed leverage is maintained, the `quote.lockedValues` is being adjusted proportionally to the `openedPrice`. The `quote.lockedValues` could adjust upward or downward during the adjustment.

However, the issue is that the adjustment is only being performed for limit orders but not for market orders. 

## Impact

The leverage factor of a market order position that is executed on-chain might end up deviating from the one at the moment the user requested due to the fluctuation of the market price. As a result, users might end up opening a position with a leverage factor higher or lower than they originally configured.

The leverage factor determines the extent of exposure to the position; thus, it might potentially magnify losses if a losing position has higher leverage than expected OR lose out on potential gain if a winning position has a lower leverage than expected.

## Code Snippet

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyB/PartyBFacetImpl.sol#L112

## Tool used

Manual Review

## Recommendation

Consider adjusting locked values for market orders to maintain the leverage, similar to what has been done for the limit orders.

**Comment by mstpr** [comment]
Escalate

"As a result, users might end up opening a position with a leverage factor higher or lower than they originally configured."
This is the idea of what market price is. If user concerns about the leverage then they should go with LIMIT order. If they go with market price it means that they are ok with whatever leverage they get at the time of execution.  Nothing wrong here. This issue is invalid

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> "As a result, users might end up opening a position with a leverage factor higher or lower than they originally configured."
> This is the idea of what market price is. If user concerns about the leverage then they should go with LIMIT order. If they go with market price it means that they are ok with whatever leverage they get at the time of execution.  Nothing wrong here. This issue is invalid 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by panprog** [comment]
Escalate

Should be low (invalid), because there is no material loss of funds. Slightly different leverage is not enough for the bug to be medium, leverage also changes each time price moves even after position is opened (since locked values are constant while the price is not), so there is no significant difference in leverage due to the bug.

I agree that there is a mismatch between handling LIMIT and MARKET quotes (in my understanding of the protocol - the only difference between MARKET and LIMIT is that LIMIT can be partially filled, but MARKET only fill or kill, so both should be handled the same), but #225 (which refers to LIMIT orders) has significant impact while this one doesn't, so should be low.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Should be low (invalid), because there is no material loss of funds. Slightly different leverage is not enough for the bug to be medium, leverage also changes each time price moves even after position is opened (since locked values are constant while the price is not), so there is no significant difference in leverage due to the bug.
> 
> I agree that there is a mismatch between handling LIMIT and MARKET quotes (in my understanding of the protocol - the only difference between MARKET and LIMIT is that LIMIT can be partially filled, but MARKET only fill or kill, so both should be handled the same), but #225 (which refers to LIMIT orders) has significant impact while this one doesn't, so should be low.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by xiaoming9090** [comment]
> Escalate
> 
> "As a result, users might end up opening a position with a leverage factor higher or lower than they originally configured." This is the idea of what market price is. If user concerns about the leverage then they should go with LIMIT order. If they go with market price it means that they are ok with whatever leverage they get at the time of execution. Nothing wrong here. This issue is invalid

Escalate

The escalation is invalid. When opening a market order, the user agrees to the market price when the transaction is executed. However, this does not mean that the user agrees to have its leverage floating (going up or down).

In the Symmetrical protocol UI (https://cloverfield.exchange/trade/BTCUSDT), users are allowed to specify the leverage of their position (e.g. 10x, up to 40x). Users expect the leverage of their position to be fixed, similar to what they have seen in the UI.

**Comment by xiaoming9090** [comment]
> Escalate
> 
> Should be low (invalid), because there is no material loss of funds. Slightly different leverage is not enough for the bug to be medium, leverage also changes each time price moves even after position is opened (since locked values are constant while the price is not), so there is no significant difference in leverage due to the bug.
> 
> I agree that there is a mismatch between handling LIMIT and MARKET quotes (in my understanding of the protocol - the only difference between MARKET and LIMIT is that LIMIT can be partially filled, but MARKET only fill or kill, so both should be handled the same), but #225 (which refers to LIMIT orders) has significant impact while this one doesn't, so should be low.

An order submitted will not be executed immediately. Depending on the network condition and gas fee provided, it might stay on the mempool for a short or long period. During this period, the price of an asset can fluctuate. For volatile assets, the price fluctuations can be pronounced, causing the deviation in the leverage to be substantial.

For small positions, the changes in the leverage might not be significant. However, for large positions (e.g. 1 million), the impact will be material. These are reasonable on-chain conditions and assumptions. Thus, it should be considered a Medium.

**Comment by panprog** [comment]
Let me give a bit more details about the leverage and why I think this issue is low or invalid. The leverage is calculated as:

`leverage = price * quantity / lockedValues.total()`

Now, since price obviously changes all the time, but quantity and locked values are constant throughout the life of the open position (until closed), **leverage changes all the time**. Basically, this protocol has floating leverage. Consider example:

1. User opens short 1 ETH position when 1 ETH = $1000 with locked values = $10, the leverage is 100. This means that 1% price move will wipe out all locked values.
2. ETH price falls to $990, locked values are still $10, so leverage is now 99
3. ETH price rises to $2000. Locked values are still $10, so leverage is now 200. Notice, that now 0.5% price move will wipe out all locked values (1% of price move can now make position in bad debt). So the position is now more risky for both users (probability of bad debt increases).

So the leverage user enters in UI is only **at the time of open position**. Say, 5 seconds after the position is opened the leverage can already be different. So yes, for MARKET orders the leverage can be slightly different when the position is opened. However, **it doesn't really matter, because the leverage will keep changing anyway**. So I'd say the leverage set in UI in just some approximate starting point.

In most futures protocols, maintaince margin is a percentage of the notional. So margin requirement (locked balance) increases when price rises and falls when price falls, it's not constant. In this protocol, maintaince margin (locked balance) is fixed, although developers attempted to fix it somewhat by scaling locked balance at the position open price (only for LIMIT quote for some reason), but in my opinion it's a flawed approach anyway, because that's basically trying to have margin requirement as percentage of notional, but only at 1 single time (position open time), which doesn't really fix anything. I'd say if developers have chosen an approach with fixed locked balance, it should be always fixed. If they want it as percentage of notional, it should always be a percentage of notional, not just at some arbitrary point in time (time of position open). If the locked balance scales only at the position open time, it's also ok, but it doesn't make much difference from not scaling it at all.

If anything, I actually find it strange that the otherwise fixed locked balance suddenly changes at position open when price is different (for LIMIT order). I'd say this is what's actually unexpected (because cva, mm and lf are fixed values, not percentages - why do they change?)

**Comment by xiaoming9090** [comment]
> Let me give a bit more details about the leverage and why I think this issue is low or invalid. The leverage is calculated as:
> 
> `leverage = price * quantity / lockedValues.total()`
> 
> Now, since price obviously changes all the time, but quantity and locked values are constant throughout the life of the open position (until closed), **leverage changes all the time**. Basically, this protocol has floating leverage. Consider example:
> 
> 1. User opens short 1 ETH position when 1 ETH = $1000 with locked values = $10, the leverage is 100. This means that 1% price move will wipe out all locked values.
> 2. ETH price falls to $990, locked values are still $10, so leverage is now 99
> 3. ETH price rises to $2000. Locked values are still $10, so leverage is now 200. Notice, that now 0.5% price move will wipe out all locked values (1% of price move can now make position in bad debt). So the position is now more risky for both users (probability of bad debt increases).
> 
> So the leverage user enters in UI is only **at the time of open position**. Say, 5 seconds after the position is opened the leverage can already be different. So yes, for MARKET orders the leverage can be slightly different when the position is opened. However, **it doesn't really matter, because the leverage will keep changing anyway**. So I'd say the leverage set in UI in just some approximate starting point.

The intended design of the protocol is not to have a floating leverage that goes up to 99x or 200x when users only specify 100x in the UI.

The intended design of the protocol is to have a fixed leverage, which can be seen in the protocol's attempt to maintain a fixed leverage for limit order [here](https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/facets/PartyB/PartyBFacetImpl.sol#L163) by scaling the locked value accordingly. This is performed to lock the leverage to take into the market price fluctuation between the time the users submit the order at the UI, and the order transaction is executed on-chain.

The discussion of the design choice taken by the protocol regarding whether the maintenance margin (or locked balance) should be a percentage of the notional or a fixed amount and whether it is optimal is irrelevant here. This report highlights an issue where the leverage can deviate. In the context of this audit, the design choice is to have a fixed amount per the source code.

**Comment by panprog** [comment]
> The discussion of the design choice taken by the protocol regarding whether the maintenance margin (or locked balance) should be a percentage of the notional or a fixed amount and whether it is optimal is irrelevant here. This report highlights an issue where the leverage can deviate. In the context of this audit, the design choice is to have a fixed amount per the source code.

The comment's intention was to give more context as to why the impact of this issue (deviation of leverage from submission time to opening position) is not medium: because leverage changes all the time after the position is opened, so the stated impact is at most low, regardless of design choice or intentions of the developers.

**Comment by Evert0x** [comment]
As I understand, purely by looking at the contracts this is not a bug. But based on the interpreted intent by the developer @xiaoming9090 was able to see that this code was not behaving as intended.  

If true, the question for the judges is if unintended behavior is a valid medium or not.

**Comment by panprog** [comment]
> But based on the interpreted intent by the developer @xiaoming9090 was able to see that this code was not behaving as intended.

As I see it:
- If intended behavior is floating leverage, this issue is invalid
- If intended behavior is fixed leverage, this issue is a drop in the sea: right after position is opened the leverage will be floating anyway, so the impact of this exact issue is insignificant anyway, even if this issue is fixed, the leverage is still floating.
- If intended behavior is fixed leverage at position open time, but then floating leverage, then this might be valid issue, however I personally find such expected behavior **very strange** so I think it's not likely.

Maybe we need developer response on what's intended behavior regarding the fixed/floating leverage? Is it possible for them to comment on it?

**Comment by MoonKnightDev** [comment]
Fixed code PR link:
https://github.com/SYMM-IO/symmio-core/pull/19

**Comment by hrishibhat** [comment]
Sponsor comment:
>  the Watsons are correct in their observation. The leverage shifts during a position's lifetime because while the locked values remain constant, the price experiences significant fluctuations. However, from a different perspective, it's beneficial to set a fixed leverage for market orders, at least at the time of opening. We've addressed this concern and have provided the solution in the linked pull request.

**Comment by panprog** [comment]
From the sponsor comment it seems the issue is valid. However, I still think it's low, because there is no material loss of funds due to this. From the sherlock medium issue criterias:
- The vulnerability must be something that is not considered an acceptable risk by a reasonable protocol team. (I think "it's beneficial to set a fixed leverage" doesn't constitute unacceptable risk)
- Causes a loss of funds but requires certain external conditions or specific states. (false)
- Breaks core contract functionality, rendering the contract useless (should not be easily replaced without loss of funds) or leading to unknown potential exploits/loss of funds. Eg: Unable to remove malicious user/collateral from the contract. (false)
- A material loss of funds, no/minimal profit for the attacker at a considerable cost (false)

**Comment by hrishibhat** [comment]
Result:
Low
Has duplicates
After further review, I agree with the points raised in the [above](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/246#issuecomment-1685200781) comment
Considering this a valid low

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [mstpr](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/246/#issuecomment-1653627810): accepted
- [panprog](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/246/#issuecomment-1653828635): accepted
