### ISSUE TITLE
xiaoming90 - Malicious PartyB cannot be removed from the protocol

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#255]
xiaoming90

medium

# Malicious PartyB cannot be removed from the protocol

## Summary

It is not possible to remove a malicious PartyB completely from the system. In the event that a PartyB turns rogue and starts performing certain actions that harm the protocol or lead to the loss of assets, it might delay or complicate the recovery process or even be unable to stop the attack in the worst-case scenario.

## Vulnerability Detail

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/control/ControlFacet.sol#L59

```solidity
File: ControlFacet.sol
59:     function registerPartyB(
60:         address partyB
61:     ) external onlyRole(LibAccessibility.PARTY_B_MANAGER_ROLE) {
62:         require(
63:             !MAStorage.layout().partyBStatus[partyB],
64:             "ControlFacet: Address is already registered"
65:         );
66:         MAStorage.layout().partyBStatus[partyB] = true;
67:         MAStorage.layout().partyBList.push(partyB);
68:         emit RegisterPartyB(partyB);
69:     }
```

To become a PartyB, the users must be registered by the protocol manager via `registerPartyB`. 

However, the protocol only has a method to register a PartyB, but does not have a method to de-register a PartyB

## Impact

In the event that a PartyB turns rogue and starts performing certain actions that harm the protocol or lead to the loss of assets, there is no way to remove the malicious PartyB from the system entirely. The protocol only has the option to suspend the malicious PartyB from calling the `withdraw` function, which might not be sufficient to guard against more sophisticated attacks.

To prove that it is insufficient, assume that the protocol suspends the malicious PartyB in an attempt to block them from calling the `withdraw` function. The attacker could exploit the issue I covered in another report to bypass this function by calling the `transferAllocation` function to transfer the assets to another account and use it to withdraw them. 

Even if the protocol has vetted PartyB at the time of registration, there is still a possibility that the private keys of PartyB be compromised by internal or external malicious actors later.

## Code Snippet

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/control/ControlFacet.sol#L59

## Tool used

Manual Review

## Recommendation

Consider implementing a new method to de-register PartyB. 

Following is the pseudo-code of the de-register method:

```solidity
function deregisterPartyB(
    address partyB
) external onlyRole(LibAccessibility.PARTY_B_MANAGER_ROLE) {
    require(
        MAStorage.layout().partyBStatus[partyB],
        "ControlFacet: Address is not registered"
    );
    MAStorage.layout().partyBStatus[partyB] = false;
    MAStorage.layout().partyBList.remove(partyB);
    emit DeregisterPartyB(partyB);
}
```

Duplicate of #229

**Comment by panprog** [comment]
Escalate

This should be low or invalid. Protocol has `suspend` functionality, which is exactly the functionality to ban malicious users. The fact that `suspended` users can still do some harmful actions is a subject of the other bug(s), but should be irrelevant in context of this bug.

While functionality to deregister partyB can be useful, it's not a security concern - this function shouldn't be used to prevent harm from malicious partyB, there is `suspend` functionality for this, even if not working as intended right now.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This should be low or invalid. Protocol has `suspend` functionality, which is exactly the functionality to ban malicious users. The fact that `suspended` users can still do some harmful actions is a subject of the other bug(s), but should be irrelevant in context of this bug.
> 
> While functionality to deregister partyB can be useful, it's not a security concern - this function shouldn't be used to prevent harm from malicious partyB, there is `suspend` functionality for this, even if not working as intended right now.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by xiaoming9090** [comment]
> Escalate
> 
> This should be low or invalid. Protocol has `suspend` functionality, which is exactly the functionality to ban malicious users. The fact that `suspended` users can still do some harmful actions is a subject of the other bug(s), but should be irrelevant in context of this bug.
> 
> While functionality to deregister partyB can be useful, it's not a security concern - this function shouldn't be used to prevent harm from malicious partyB, there is `suspend` functionality for this, even if not working as intended right now.

Escalate

It is not true that one report can contain only one bug and other bugs are considered irrelevant, as mentioned by the escalator. In fact, one is allowed to chain multiple bugs to form a more severe bug.

As mentioned in my impact section, the suspend function can only restrict the withdrawal ability of PartyB. However, it can be bypassed via the `transferAllocation`. This effectively means that there is no way to remove the malicious PartyB from the system entirely.

In the report, I have demonstrated how chaining up two (2) issues could lead to a medium-risk issue.

**Comment by panprog** [comment]
> It is not true that one report can contain only one bug and other bugs are considered irrelevant, as mentioned by the escalator. In fact, one is allowed to chain multiple bugs to form a more severe bug.

I didn't say that. However, the demonstrated impact (malicious partyB can not be stopped from continuing doing harm) is already the impact of the other issue like #229 (`suspend` functionality still allowing some actions for suspended user). It's incorrect to claim that lack of deregister functionality + incorrect `suspend` functionality causes inability to stop malicious partyB, because incorrect `suspend` functionality alone is already enough and is the root cause of this problem, you don't have to add anything else to it.

I can say: "There should be function ban() to ban user from all actions in the protocol, because suspend functionality intends to do the same but fails to achieve it". Why `deregisterPartyB`? Why not `ban` to ban any user (even liquidator)?

My point is that there is already a function to prevent the stated impact, it just works incorrectly.

**Comment by xiaoming9090** [comment]
There are two distinct root causes and solutions here:
- Issue https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/255 - Root Cause: Lack of ability to remove malicious PartyB address from the system. Solution: Implement a new method to de-register PartyB.
- Issue https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/229 - Root cause: Lack of `notSuspended` modifier on the affected functions. Solution: Add the `notSuspended` modifier to the affected functions.

The `transferAllocation` bypass that I mentioned in the impact section is only one of the possible examples of a serious consequence that could happen if there is no de-register function exist in the context of the current codebase, which contains a bug in `transferAllocation`.

Besides that, the impact section of this report mentioned that having the option to suspend the malicious PartyB from calling the withdraw function might not be sufficient to guard against more sophisticated attacks. When a protocol is under attack or on the verge of an exploit, the protocol needs the option to remove the malicious PartyB entirely from the system. Blocking the withdrawal might not be enough, as withdrawal is just one of the many functions (e.g. lockQuote, openPosition) that PartyB can utilize. 

For instance, some reported issues in this contest already involve malicious PartyB that do not utilise withdrawal feature. Simply suspending the withdrawal of a malicious PartyB account would not block these attacks at all for this type of exploit, and the attack will persist. So the quickest and best action that a protocol team can take once such an exploit is discovered is to remove the malicious PartyB address from the system. These are reasonable external conditions and thus should be a Medium.

**Comment by panprog** [comment]
> Blocking the withdrawal might not be enough, as withdrawal is just one of the many functions (e.g. lockQuote, openPosition) that PartyB can utilize.

My point is that `suspend` functionality is obviously there to stop any user from doing any harm to the protocol, it **should** stop many different functions, not just the withdrawal. The fact that `suspend` functionality only stops withdrawals **is** a bug. Once `suspend` is fixed to stop any harmful actions, there will be no need to deregister partyB in case it's malicious - suspending it should be enough.

This means that stated impact's core reason is **not** because there is a lack of deregister partyB functionality, but because the existing `suspend` functionality is broken, so the real impact of this issue is low.

**Comment by Evert0x** [comment]
@xiaoming9090 I tend to agree with @panprog here. It seems like `deregisterPartyB` would have a similar outcome as a well functioning `suspend` function. So the core issue is described in #229 already.

**Comment by MoonKnightDev** [comment]
Fixed code PR link:
https://github.com/SYMM-IO/symmio-core/pull/2

**Comment by xiaoming9090** [comment]
> @xiaoming9090 I tend to agree with @panprog here. It seems like `deregisterPartyB` would have a similar outcome as a well functioning `suspend` function. So the core issue is described in #229 already.

Noted with thanks.

**Comment by hrishibhat** [comment]
Result:
Medium 
Duplicate of #229

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [panprog](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/255/#issuecomment-1653869638): accepted
