### ISSUE TITLE
Kose - System can get into a state where user actions are paused while liquidations not

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#281]
Kose

medium

# System can get into a state where user actions are paused while liquidations not

## Summary
It is possible to unfairly liquidate a user because user can not allocate any value to their positions because of pausing states.
## Vulnerability Detail
In order to avoid going into liquidation (for any party) user's can:
- close their positions(1)
- deposit and allocate new funds to their positions(2) 
- open hedge positions with some other party(3). 

However, it is very possible that users will not be able to use any of these solutions because of pausing states.
While there are too many scenarios that this situation can happen (because of too many pausing states) let's consider the easiest one:
1. PartyA has very negative upnl and will go into liquidation if won't do anything.
2. PartyA doesn't have any free balance to open new positions hence solution number 1 and 3 is impossible, only way is solution 2.
3.  Accounting is paused hence partyA can not deposit and allocate funds to avoid liquidation.
4. Liquidations are not paused, hence after some time partyA gets liquidated.

There are of course multiple scenarios that this situation can occur. For example If partyA actions are paused then even if partyA has allocated free balance, solution 1 and 3 won't work. Same is true for partyB as well.

## Impact
Users can not prevent their liquidation in certain pausing states hence get liquidated unfairly.

## Tool used

Manual Review

## Code Snippets
[AccountFacet.sol](https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/Account/AccountFacet.sol/#L13-L55)
```solidity
 function deposit(uint256 amount) external whenNotAccountingPaused {
        AccountFacetImpl.deposit(msg.sender, amount);
        emit Deposit(msg.sender, msg.sender, amount);
    }

    function depositFor(address user, uint256 amount) external whenNotAccountingPaused {
        AccountFacetImpl.deposit(user, amount);
        emit Deposit(msg.sender, user, amount);
    }
...
 function allocate(
        uint256 amount
    ) external whenNotAccountingPaused notLiquidatedPartyA(msg.sender) {
        AccountFacetImpl.allocate(amount);
        emit AllocatePartyA(msg.sender, amount);
    }
```
(One example for partyA has been provided above. Consider all functions that won't work in paused states)

## Recommendation
Never put system into a state where repayments are paused and liquidations are enabled. Require that in order to put system into any of these situations:
-Accounting Paused
-PartyA Actions Paused
-PartyB Actions Paused
Liquidations must be first paused.

Duplicate of #336

**Comment by kosedogus** [comment]
Escalate

System does not enforce the liquidations to be paused while party actions or accounting is paused. While I don't fully understand why this issue was not accepted, I would like to point out the sponsor's comment in [#227](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/227):
> When we are setting the symbol trading fee, we pause actions for party A. This ensures that no one can send a quote before this process, and we also verify that no quote is open prior to it.

Although the issue is alone sufficient to show the vulnerability, the comment made by sponsor further strengthens the possibility for this vulnerability to occur. As we can see, protocol pause actions for partyA when setting trading fee. Hence during this time because partyA can not do anything to clear their position they can be liquidated. Again this is just one of many scenarios. Protocol might plan to pause PartYA || PartyB || Accounting in any other time while planning to do some benign actions such as upgrading tradeFee without pausing liquidations. There are no code piece in the codebase that will prevent this to happen.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> System does not enforce the liquidations to be paused while party actions or accounting is paused. While I don't fully understand why this issue was not accepted, I would like to point out the sponsor's comment in [#227](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/227):
> > When we are setting the symbol trading fee, we pause actions for party A. This ensures that no one can send a quote before this process, and we also verify that no quote is open prior to it.
> 
> Although the issue is alone sufficient to show the vulnerability, the comment made by sponsor further strengthens the possibility for this vulnerability to occur. As we can see, protocol pause actions for partyA when setting trading fee. Hence during this time because partyA can not do anything to clear their position they can be liquidated. Again this is just one of many scenarios. Protocol might plan to pause PartYA || PartyB || Accounting in any other time while planning to do some benign actions such as upgrading tradeFee without pausing liquidations. There are no code piece in the codebase that will prevent this to happen. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ctf-sec** [comment]
> System does not enforce the liquidations to be paused while party actions or accounting is paused

this is true

but consider admin is trusted 

this falls into the category of incorrect call order

https://docs.sherlock.xyz/audits/judging/judging

> Admin Input/call validation:  Protocol admin is considered to be trusted in most cases, hence issues where

> Admin incorrectly enters an input parameter. Example: Make sure interestPerMin > 1 ether as it is an important parameter.  This is not a valid issue.

> Admin could have an incorrect call order. Example: If an Admin forgets to setWithdrawAddress() before calling withdrawAll() This is not a valid issue.

**Comment by kosedogus** [comment]
Not at all, admin can be trusted and pause partyA actions without pausing liquidations, this exact situation is written above which protocol is planning to do. If admin don't pause liquidation while pausing other states, that doesn't make them malicious at all. It is very normal thing to do if we don't consider this vulnerability I submitted. And this vulnerability states that this shouldn't be possible state for protocol, because this state create unfair liquidations. What you call incorrect call order is totally different from what I submitted. In your example it is obvious that in order to withdrawAll() you need to setWithdrawAddress(), this call order doesn't show any attack vector other than basic admin error.  But pausing liquidations before pausing repayments is not an obvious thing, one admin can safely assume that it is safe to pause repayments without pausing liquidations if he/she don't know about this vulnerability. And we can see that they are actually planning to do this (very normal). But anyone can understand in order to withdraw you have to setWithdrawAddress, there is no need for explanation for this kind of thing. So this issue is not incorrect call order issue, it explains a state where system can easily be in in many situations, but also a state where system shouldn't be in. Hence it should be addressed.

**Comment by kosedogus** [comment]
I want to add an example from [Blueberry#290](https://github.com/sherlock-audit/2023-02-blueberry-judging/issues/290). For example in this codebase, there wasn't even liquidation pause, and because of that it creates an even more problematic situation. But the solution that is recommended and implemented by protocol is : they check if repayment's paused or not during liquidation, if it is they don't allow to liquidate. This is basically a safeguard that needs to be implemented by any protocol that has liquidation process. However in the symmetrical's codebase there is no safeguard to protect from this situation and the protocol is planning to use pausing states for different benign purposes (for example pausing partyA actions during upgrade to TradeFee). Liquidations shouldn't even be possible during other pausing states, that is what vulnerability is about and this is a very likely situation without a need for malicious admin / admin error (We obviously don't know if admin is aware of this vulnerability prior to contest and from the comments made by them it is very likely that they don't).

**Comment by hrishibhat** [comment]
Result:
Medium
Duplicate of #336 
Considering this issue a valid duplicate of  #336 as the underlying issue is the same

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [kosedogus](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/281/#issuecomment-1651707524): accepted
