### ISSUE TITLE
mstpr-brainbot - Redundant profit/loss check in close position

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-symmetrical-judging#87]
mstpr-brainbot

high

# Redundant profit/loss check in close position

## Summary
When PartyA (Alice) proposes to close a trading position, she submits her desired closing price. If PartyB (Bob) agrees, an additional Profit/Loss (PNL) check happens within the system if the desired close price isn't the same as the current market price. This additional check seems redundant since a system component, the Muon oracle, already considers the current market price to calculate PNL for both parties.
## Vulnerability Detail
Whenever PartyA decides to close a position, they specify a desired closing price. If PartyB agrees to close the position and the requested closing price is different from the current market price, an extra profit/loss (PNL) check is executed within the code. However, this additional step seems unnecessary, given the Muon oracle already assesses the PNL for both parties using the current market price.

Let's illustrate this with an example: Alice, holding a (quantity 1) LONG Ethereum (ETH) position, intends to exit the trade when ETH reaches a price of $2000. The prevailing market price, though, is $1800. Alice goes ahead and sends a close request to Bob, her counterparty for this trade.

Fast forward to when Bob agrees to close the position, and the market price of ETH has risen to $2010. As part of the closing process, the 'fillCloseRequest' function triggers the 'LibSolvency.isSolventAfterClosePosition'.

```solidity
Quote storage quote = QuoteStorage.layout().quotes[quoteId];
        uint256 unlockedAmount = (filledAmount * (quote.lockedValues.cva + quote.lockedValues.lf)) /
            LibQuote.quoteOpenAmount(quote);

        int256 partyBAvailableBalance = LibAccount.partyBAvailableBalanceForLiquidation(
            upnlSig.upnlPartyB,
            quote.partyB,
            quote.partyA
        ) + int256(unlockedAmount);

        int256 partyAAvailableBalance = LibAccount.partyAAvailableBalanceForLiquidation(
            upnlSig.upnlPartyA,
            quote.partyA
        ) + int256(unlockedAmount);

        require(
            partyBAvailableBalance >= 0 && partyAAvailableBalance >= 0,
            "LibSolvency: Available balance is lower than zero"
        );
        if (quote.positionType == PositionType.LONG) {
            if (closedPrice >= upnlSig.price) {
                require(
                    uint256(partyBAvailableBalance) >=
                        ((filledAmount * (closedPrice - upnlSig.price)) / 1e18),
                    "LibSolvency: PartyB will be liquidatable"
                );
            } else {
                require(
                    uint256(partyAAvailableBalance) >=
                        ((filledAmount * (upnlSig.price - closedPrice)) / 1e18),
                    "LibSolvency: PartyA will be liquidatable"
                );
            }
        } else if (quote.positionType == PositionType.SHORT) {
            if (closedPrice <= upnlSig.price) {
                require(
                    uint256(partyBAvailableBalance) >=
                        ((filledAmount * (upnlSig.price - closedPrice)) / 1e18),
                    "LibSolvency: PartyB will be liquidatable"
                );
            } else {
                require(
                    uint256(partyAAvailableBalance) >=
                        ((filledAmount * (closedPrice - upnlSig.price)) / 1e18),
                    "LibSolvency: PartyA will be liquidatable"
                );
            }
        }
        return true;
    }
```

From the code snippet above, we can see the process begins by calculating the available balances factoring in the PNL. Notably, the PNL passed to the LibAccount functions is based on the prevailing market price, not Alice's requested close price.

With a quantity of 1, the current ETH price is $2010, and the open price was $1800. This gives Alice a PNL of (2010-1800) * 1 = 210.

Assume Bob's total cva+lf is 180 and mm is 219. Calculating Bob's total locked balances, we get 399 - 180 - 210 = 9. As Bob's balance of 9 is greater than zero, he is not in danger of liquidation.

The PNL calculation used the current price of $2010, not Alice's requested close price of $2000. Continuing down the code, an 'if' condition is executed. Since $2010 is greater than $2000 and Alice's position is LONG, we trigger the following statement:

require(9 >= 1 * (2010-2000))
require(9 >= 10)

Consequently, the transaction would fail. Even though Bob's PNL was based on the current price, an additional check incorporates another price factor, which has already been covered in the Muon oracles' pnl argument. 

## Impact
Double counting the extra pnl, unintended and not consistent with the design
## Code Snippet
https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/facets/PartyB/PartyBFacetImpl.sol#L256-L293

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/libraries/LibSolvency.sol#L99-L154

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/libraries/LibAccount.sol#L78-L86

https://github.com/sherlock-audit/2023-06-symmetrical/blob/main/symmio-core/contracts/libraries/LibAccount.sol#L144-L155

Muon part
```solidity
calculateUpnl: async function (openPositions, prices) {
    let uPnl = new BN(0); // Initializes uPnl to zero
    let loss = new BN(0); // Initializes loss to zero
    let notionalValueSum = new BN(0); // Initializes notionalValueSum to zero

    // Iterates through each open position
    for (let [i, position] of openPositions.entries()) {
        const openedPrice = new BN(position.openedPrice); // Retrieves the opened price of the position
        const priceDiff = new BN(prices[i]).sub(openedPrice); // Calculates the price difference between the current price and the opened price
        const amount = new BN(position.quantity).sub(new BN(position.closedAmount)); // Calculates the remaining amount of the position

        // Calculates the uPnl for the current position based on the position type (long or short)
        const longPositionUpnl = amount.mul(priceDiff);
        const positionUpnl = position.positionType == '0' ? longPositionUpnl : minusOne.mul(longPositionUpnl);

        // Adds the position's uPnl to the total uPnl after scaling it
        uPnl = uPnl.add(positionUpnl.div(scale));
        // Add the position's uPnl to the total loss if it is negative
        if (positionUpnl.isNeg()) loss = loss.add(positionUpnl.div(scale));

        // Calculates the notional value of the position and adds it to the total notional value sum
        const positionNotionalValue = amount.mul(openedPrice).div(scale);
        notionalValueSum = notionalValueSum.add(positionNotionalValue);
    }

    // Returns the calculated uPnl and notional value sum
    return { uPnl, loss, notionalValueSum };
},
```
## Tool used

Manual Review

**Comment by mstpr** [comment]
Escalate

I think this is a valid finding. I double checked the above scenario and it was consistent.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> I think this is a valid finding. I double checked the above scenario and it was consistent.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by MoonKnightDev** [comment]
Yes, the market price is factored into the UPNL calculation, which is exactly why we need another check. The issue lies in the fact that the user's profit is not based on a price of 2010, but rather it's calculated with the closing price, which is 2000. This situation is disadvantageous for the user. Therefore, we need to ensure that the user remains clear of liquidation even when the price is equal to 2000.

**Comment by mstpr** [comment]
@MoonKnightDev 

The "pnl" that calculated in Muon app is: `marketPrice - openedPrice` not closedPrice - openedPrice. It means that pnl is already calculated the correct pricing (current price not closed price) and contract double counts it. 

https://github.com/sherlock-audit/2023-06-symmetrical/tree/main/symmio-core/muon#calculateupnl

**Comment by panprog** [comment]
The following is **not true**

> The PNL calculation used the current price of $2010, not Alice's requested close price of $2000. Continuing down the code, an 'if' condition is executed. Since $2010 is greater than $2000 and Alice's position is LONG, we trigger the following statement:

`isSolventAfterClosePosition` uses `closedPrice`, which is the price provided by the partyB to close position (2010 in the example), not the price requrested by Alice (2000), so in the example closedPrice = 2010 = upnlSig.price, so no additional check is done:

```solidity
            if (closedPrice >= upnlSig.price) {
                require(
                    uint256(partyBAvailableBalance) >=
                        ((filledAmount * (closedPrice - upnlSig.price)) / 1e18),
                    "LibSolvency: PartyB will be liquidatable"
                );
            } else {
```

There are the following values:
`closedPrice`: price provided by partyB to close position
`quote.requestedClosePrice`: price requested by partyA
`upnlSig.price`: market price

This report implies that `quote.requestedClosePrice` is used in the solvency check, but actually `closedPrice` is used, thus the solvency check is correct.

**Comment by mstpr** [comment]
> The following is **not true**
> 
> > The PNL calculation used the current price of $2010, not Alice's requested close price of $2000. Continuing down the code, an 'if' condition is executed. Since $2010 is greater than $2000 and Alice's position is LONG, we trigger the following statement:
> 
> `isSolventAfterClosePosition` uses `closedPrice`, which is the price provided by the partyB to close position (2010 in the example), not the price requrested by Alice (2000), so in the example closedPrice = 2010 = upnlSig.price, so no additional check is done:
> 
> ```solidity
>             if (closedPrice >= upnlSig.price) {
>                 require(
>                     uint256(partyBAvailableBalance) >=
>                         ((filledAmount * (closedPrice - upnlSig.price)) / 1e18),
>                     "LibSolvency: PartyB will be liquidatable"
>                 );
>             } else {
> ```
> 
> There are the following values: `closedPrice`: price provided by partyB to close position `quote.requestedClosePrice`: price requested by partyA `upnlSig.price`: market price
> 
> This report implies that `quote.requestedClosePrice` is used in the solvency check, but actually `closedPrice` is used, thus the solvency check is correct.

closedPrice is 2000$ in the example not 2010$. 2010$ is the current market price.

problem here is that the pnl calculated always marketPrice - openedPrice which already accounts the difference

**Comment by panprog** [comment]
> closedPrice is 2000$ in the example not 2010$. 2010$ is the current market price.
> problem here is that the pnl calculated always marketPrice - openedPrice which already accounts the difference

Ok, got you, I think you mis-read the code then. In this case (LONG position, close price < market price), the `require` will be for partyA (Alice), not for Bob:
```solidity
            } else {
                require(
                    uint256(partyAAvailableBalance) >=
                        ((filledAmount * (upnlSig.price - closedPrice)) / 1e18),
                    "LibSolvency: PartyA will be liquidatable"
                );
            }
```

The logic is the following:
- Alice UPNL from muon app calculates it at the market price ($2010)
- However, real close price ($2000) is lower, meaning real Alice profit from the position closure will less than UPNL
- That's why an additional check is required to ensure that Alice is still solvent when this difference is accounted for.

In your example just replace Bob with Alice and it becomes correct:

> Assume Bob's total cva+lf is 180 and mm is 219. Calculating Bob's total locked balances, we get 399 - 180 - 210 = 9. As Bob's balance of 9 is greater than zero, he is not in danger of liquidation.
> 
> The PNL calculation used the current price of $2010, not Alice's requested close price of $2000. Continuing down the code, an 'if' condition is executed. Since $2010 is greater than $2000 and Alice's position is LONG, we trigger the following statement:
> 
> require(9 >= 1 * (2010-2000)) require(9 >= 10)

So, Alice balance is 9 (when calculated at the closing price of $2010). But Alice balance becomes -1 if closed at the price of $2000, so require (9 >= 1 * (2010-2000)) will revert, which is correct, because Alice will be insolvent if closed at this price.

**Comment by mstpr** [comment]
@panprog 

Alice is partyA
Bob is partyB

Alice and Bob has a quote together. 1 LONG ETH with open price of 1800$. 

Alice sends a close request to Bob at price 2000$. 

Bob closes the position at requested price of 2000$ when the price of ETH is 2010$. 

PNL calculated for Alice is (2010 - 1800) * 1 = 210$ (current price - open price) * quantity and -210 for Bob.

Now, let's also assume Alice has bunch of other trades with other partyB's and say that she has -420 pnl with others.
This means that Alice has -420 with others and +210 with Bob and in total she has -210 pnl. 

Now, Bob calls fillCloseRequest with closedPrice == 2000$ 

Let's do the LibSolvency. isSolventAfterClosePosition

From the example in issue let's take these balances as an example: 
Assume Alice's total cva+lf is 180 and mm is 219

partyAAvailableBalance(Alice) will be calculated with this function:

```solidity
function partyAAvailableBalanceForLiquidation(
        int256 upnl,
        address partyA
    ) internal view returns (int256) {
        AccountStorage.Layout storage accountLayout = AccountStorage.layout();
        int256 freeBalance = int256(accountLayout.allocatedBalances[partyA]) -
            int256(accountLayout.lockedBalances[partyA].cva + accountLayout.lockedBalances[partyA].lf);
        return freeBalance + upnl;
    }
```

a = (180+219) - (180) = 219
return 219 + (-210) = 9
so Alice's available balance is 9 after this function which is correctly calculated so far. She is not liquidatable.

now let's move on with function, we have this if check 

```solidity
 if (quote.positionType == PositionType.LONG) {
            if (closedPrice >= upnlSig.price) {
                require(
                    uint256(partyBAvailableBalance) >=
                        ((filledAmount * (closedPrice - upnlSig.price)) / 1e18),
                    "LibSolvency: PartyB will be liquidatable"
                );
            } else {
                require(
                    uint256(partyAAvailableBalance) >=
                        ((filledAmount * (upnlSig.price - closedPrice)) / 1e18),
                    "LibSolvency: PartyA will be liquidatable"
                );
            }
        }
```

our position is LONG, upnlSig.price = 2010, closedPrice = 2000

means that we will do the second 'else' statement.

9 >= 1 * (2010 - 2000) 
which is wrong.

So the position is LONG and Alice is in profit, this check is imo is redundant. Why is this check here? Why partyA would be liquidatable in this scenario? 
if partyA is not liquidatable in the first check at here:
https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/libraries/LibSolvency.sol#L120-L123
then they are not going to be liquidatable in this require check because this case is actually positive for partyA. 


Note: I checked my issue and you are right, I confused the Alice-Bob example there. Thanks for taking a detailed look, appreciate it!

**Comment by panprog** [comment]
> So the position is LONG and Alice is in profit, this check is imo is redundant. Why is this check here? Why partyA would be liquidatable in this scenario?

Just continue with your calculation and see Alice balance if the fill request proceeds without this check.

Alice allocated balance is 219. The position with Bob is closed at a price of 2000 with a profit of 1 * (2000-1800) = 200. Alice allocated balances becomes 419. Now Alice upnl with the other parties is -420 (her profitable position of +210 is removed from her account). Alice unrealzed loss (-420) is now larger than her balance (419), so she's insolvent.

I think that confusion lies in that a profit can't make Alice position worse, but it can, because profit or loss is irrelevant in isolation: when a profit is realized to Alice account, at the same time a profitable position is removed from Alice account, meaning total account value will reduce if added collateral value is less than removed profitable position's profit.

**Comment by mstpr** [comment]
> > So the position is LONG and Alice is in profit, this check is imo is redundant. Why is this check here? Why partyA would be liquidatable in this scenario?
> 
> Just continue with your calculation and see Alice balance if the fill request proceeds without this check.
> 
> Alice allocated balance is 219. The position with Bob is closed at a price of 2000 with a profit of 1 * (2000-1800) = 200. Alice allocated balances becomes 419. Now Alice upnl with the other parties is -420 (her profitable position of +210 is removed from her account). Alice unrealzed loss (-420) is now larger than her balance (419), so she's insolvent.
> 
> I think that confusion lies in that a profit can't make Alice position worse, but it can, because profit or loss is irrelevant in isolation: when a profit is realized to Alice account, at the same time a profitable position is removed from Alice account, meaning total account value will reduce if added collateral value is less than removed profitable position's profit.

function ends there I can't continue 😄 

Alice total pnl is -210, -420 loss and +210 profit she is solvent as the calculation goes.

profit calculated is not 2000-1800, its 2010-1800. 

profit can't make Alice go insolvent if she is not insolvent at the first place, Alice is not isolated, Alice is cross trading since she can have bunch of other trades with other partyB's. 

Please do me a scenario like I did above otherwise I don't think we will settle on a decision

**Comment by panprog** [comment]
> function ends there I can't continue 😄

I mean, you say that the check is not needed. Then just continue the `fillCloseRequest()` as if there was no such check and see what happens with Alice position.

> profit calculated is not 2000-1800, its 2010-1800.

The unrealized profit which is provided by muonapp is based on market price of $2010, so upnl is +210-420 = -210 for Alice.
However, realized profit when position is closed is calculated by actual close price ($2000), so realized profit is $200, and this is what's added to Alice allocated balance at the position close time:
https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/libraries/LibQuote.sol#L111

current price here is the close price:
https://github.com/sherlock-audit/2023-06-symmetrical/blob/6d2b64b6732fcfbd07c8217897dd233dbb6cd1f5/symmio-core/contracts/libraries/LibQuote.sol#L169-L173

> Please do me a scenario like I did above otherwise I don't think we will settle on a decision

Alice has 2 open positions:
1. 1 ETH long position with Bob with open price = $1800. cva+lf=5. mm=5.
2. 4 ETH short position with Charlie with open price = $1905. cva+lf=83. mm=83.

Alice's allocated balance is 300. Total locked values = 5+5+83+83=176. Total cva+lf = 88.
At the market price of $2000 Alice requests to close her 1 ETH long position at the price of $2000 (at this point she's solvent: upnl = 1 * (2000 - 1800) - 4 * (2000 - 1905) = 200 - 380 = -180, balance=300. 300 - 180 = 120 > 88)
Once the market price reaches $2010, Alice is still solvent:
upnl = 1 * (2010-1800) - 4 * (2010-1905) = 210 - 420=-210
allocated balance = 300
300 - 210 = 90 > 88 - Alice still solvent.

Now, Bob calls `fillCloseRequest()` with the closePrice = $2000.

Let's pretend that the extra check you say is not needed - is not performed. Alice is solvent at the market price of $2010, so the `fillCloseRequest()` proceeds to close the position (at the closePrice = $2000).
Alice profit from the position = 1 * (2000 - 1800) = $200. In your last comment you say that it's $210 - but no. This is realized profit, which is added to Alice allocatedBalance at the closePrice which is equal Alice requested price of $2000. So $210 is "imaginary" (unrealized) profit, but "real" (realized) profit is less than that, it's $200.
So the position is closed and Alice allocated balance increases by $200. Alice now has allocated balance of $500. She now only has 4 ETH short position with Charlie, so locked balances also decrease to just that position: cva+lf=83, mm=83.
4 ETH short position has upnl=-4*(2010-1905) = -420
Alice allocated balance is $500.
So Alice is now insolvent: $500-$420 = $80 < 83 (cva+lf)

This means she should have been prevented from closing. That's why that check is needed. If that additional check was performed, then that check would have reverted.

When I've talked about profit or loss not meaning anything in isolation, I didn't mean isolated position :) What I've meant is this:
Account Value = Allocated Balance + Unrealized Profit and Loss
What matters is Account Value - if it decreases, account becomes insolvent. And it doesn't matter if there is a profit or loss. For example:
100 = 400 - 300 (unrealized loss of -300)
100 = 50 + 50 (unrealized profit of +50)
These are exactly the same situations. So it doesn't matter if account is in profit or in loss - in both cases it's possible to be liquidated. Even if account has only 1 position and is in profit, it can easily be liquidated! For example, if cva+lf = 120, then account with allocated balance of 50 and unrealized profit of +50 will be insolvent (this can happen if account deallocates when profit is big, and then profit decreases and account becomes insolvent).

What happens in the situation which you describe in your report is basically this:
Account value = 300 - 210 = 90 > 88 (cva+lf = 88 - account is solvent)
After position is closed, the realized amount is less than profit, so it becomes:
Account value = 500 - 420 = 80 < 83 (cva+lf = 83 - account is insolvent)

**Comment by mstpr** [comment]
@panprog 
ok, after checking the LibQuote I see what you saying. I thought unrealized pnl is always realizable at anytime but that's not the case. 

Thanks for your patience and enlightenment, appreciate it. 

@hrishibhat This escalation should be rejected.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non issue based on the above comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [mstpr](https://github.com/sherlock-audit/2023-06-symmetrical-judging/issues/87/#issuecomment-1653734950): rejected
